Technology column
ProjectDrawdown/global-research-platform pull request #89
Opened 2021-07-29 21:31 UTC by brodavi

adding "technology" column

apologies for the tab->spaces formatting, python wasn't digging the mixed indenting.

I tested with a temp api call to `/resource/vma/info/{tech}/{name}` from React, seemed to work.

`name` is now the file name without any of the path, and in theory can be anything the user likes.

2021-07-30 16:46 UTC, sutjin requested changes

2021-07-30 16:46 UTC, sutjin commented on service/api/db/models.py
> +    technology = Column(String)
Once we added it to the `Resource` class, we shouldnt need to redeclare it on the other classes that inherits the `Resource` class

2021-07-30 16:46 UTC, sutjin commented on service/api/queries/resource_queries.py
> +    print(f"name: {name}, technology: {technology}, table: {table}, user: {user}")
remove print statement

2021-08-02 16:17 UTC, brodavi commented
@sutjin okay I removed the print statement and unnecessary column definitions. I didn't resolve the conflicts, it looks like the most recent develop doesn't conflict?

2021-08-02 17:24 UTC, sutjin approved these changes

2021-08-02 18:05 UTC, merged